#!/usr/bin/env python

import argparse

from buzz.corpus import Corpus

"""
A script to parse using buzz

:Example:

$ parse junglebook --cons-parser bllip

"""

parser = argparse.ArgumentParser(description='Parse a corpus.')

parser.add_argument(
    '-l',
    '--language',
    nargs='?',
    default='english',
    type=str,
    required=False,
    help='Language of the corpus',
)

parser.add_argument(
    '-p',
    '--cons-parser',
    nargs='?',
    default='benepar',
    type=str,
    required=False,
    choices=['bllip', 'benepar'],
    help='Constituency parser to use (bllip/benepar)',
)

parser.add_argument('path', help='Directory containing files to parse')

kwargs = vars(parser.parse_args())

corpus = Corpus(kwargs.pop('path'))

corpus.parse(**kwargs)
